### ISSUE TITLE
TypeError: 'module' object is not callable

### ISSUE THREAD

**Issue by ghost** [openedoo/module_employee#6]
127.0.0.1 - - [03/Apr/2017 17:25:20] "GET /employee/ HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/dwi/kerja/venv2/lib/python2.7/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/dwi/kerja/venv2/lib/python2.7/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/home/dwi/kerja/venv2/lib/python2.7/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/dwi/kerja/venv2/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/dwi/kerja/venv2/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/dwi/kerja/venv2/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/dwi/kerja/venv2/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/dwi/kerja/venv2/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/dwi/kerja/venv2/lib/python2.7/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/dwi/kerja/venv2/openedoo_project/modules/module_employee/controllers/public.py", line 10, in dispatch_request
    for m, x in session.query(models.Employee.us

**Comment by ghost** [comment]
@rendiya

**Comment by ghost** [comment]
i dont know why, but i get this working when i try with different machine. i will compare my project setup tomorrow to inspect what is wrong.
